### ISSUE TITLE
Render tool incorrectly parses Markdown.

### ISSUE THREAD

**Issue by MineRobber9000** [tildetown/tilde-rfcs#1]
The render tool parses Markdown badly. (After all, a plaintext parse for Markdown isn't the greatest.) Namely, it forgets the first letter of the author line. (see [here (md)](http://tilde.town/~minerobber/tilderfcs/0.md.html) and [here (text)](http://tilde.town/~minerobber/tilderfcs/0.txt.html))

**Comment by vijaygomathinayagam** [comment]
I'm on it

**Comment by MineRobber9000** [comment]
Fixed by #3 and closed.
